site_name: WWIA 
nav:
  - Home: index.md

  - Foundations:
      - Overview: 01-foundations/index.md
      - Networking:
          - Overview: 01-foundations/networking/index.md
      - Operating Systems:
          - Overview: 01-foundations/operating-systems/index.md
      - Memory & Execution:
          - Overview: 01-foundations/memory-and-execution/index.md
      - Cryptography:
          - Overview: 01-foundations/cryptography/index.md
      - Scripting:
          - Overview: 01-foundations/scripting/index.md

  - Offensive Security:
      - Overview: 02-offensive-security/index.md
      - Reconnaissance:
          - Overview: 02-offensive-security/reconnaissance/index.md
      - Initial Access:
          - Overview: 02-offensive-security/initial-access/index.md
      - Exploitation:
          - Overview: 02-offensive-security/exploitation/index.md
      - Post-Exploitation:
          - Overview: 02-offensive-security/post-exploitation/index.md
      - Malware:
          - Overview: 02-offensive-security/malware/index.md

  - Defensive Security:
      - Overview: 03-defensive-security/index.md
      - Prevention:
          - Overview: 03-defensive-security/prevention/index.md
      - Detection:
          - Overview: 03-defensive-security/detection/index.md
      - Monitoring & Response:
          - Overview: 03-defensive-security/monitoring-and-response/index.md
      - Security Architecture:
          - Overview: 03-defensive-security/security-architecture/index.md

  - Concepts:
      - Overview: 04-concepts/index.md

  - How-To ____:
      - Overview: 05-how-to/index.md

  - Demos & Projects:
      - Overview: 06-demos-projects/index.md

theme:
  name: readthedocs 
  user_color_mode_toggle: true
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s